name: Continuous Testing and Docs Publication

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
  push:
    branches:
      - dev
  workflow_dispatch:
  schedule:
    # At 02:00 on Sunday: https://crontab.guru/#0_2_*_*_0
    - cron: "0 2 * * 0"

jobs:
  run-linter:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Echo something
        run: |
          echo "I am running!"
          date
