name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # At 02:00 on Sunday: https://crontab.guru/#0_2_*_*_0
    - cron: "0 2 * * 0"

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Echo something
        run: |
          echo "I am running!"
          date

      - name: Github Action to keep the schedules alive after inactivity
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: mrakitin
          committer_email: mrakitin@users.noreply.github.com
          time_elapsed: 2  # days
